# See https://pre-commit.com/hooks.html for more hooks
# See https://pre-commit.com for more information
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: master
    hooks:
      - id: check-ast
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: fix-encoding-pragma
      - id: check-docstring-first
      - id: check-executables-have-shebangs
      - id: check-json
      - id: pretty-format-json
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-toml
      - id: check-xml
      - id: check-added-large-files
      - id: check-yaml
      - id: debug-statements
      - id: name-tests-test
      - id: requirements-txt-fixer

  - repo: https://github.com/pre-commit/mirrors-pylint
    rev: master # Use the sha / tag you want to point at
    hooks:
      - id: pylint

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: master
    hooks:
      - id: mypy
        language_version: python3.8
        args:
          [
            --ignore-missing-imports,
            --warn-redundant-casts,
            --warn-unused-ignores,
            --warn-return-any,
            --warn-unreachable,
            --disallow-untyped-calls,
            --disallow-untyped-defs,
            --disallow-incomplete-defs,
            --check-untyped-defs,
            --disallow-untyped-decorators,
          ]

  - repo: https://github.com/ambv/black
    rev: stable
    hooks:
      - id: black
        language_version: python3.8
